Controllers/ClientsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Strona.Database;
using Strona.Entities;
using Strona.Models;
using Strona.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Strona.Controllers
{
    public class ClientsController : Controller
    {
        
        private readonly IClientService _clientService;

        public ClientsController(IClientService clientService)
        {
            
            _clientService = clientService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(ClientModel client)
        {
            await _clientService.Add(client);

            return View();
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> List(string name)
        {
            var clients = await _clientService.GetAllClients(name);
            return View(clients);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>@ViewData["Title"] Strona</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <link href="~/assets/css/style.css" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet">
    <script>
        window.addEventListener("DOMContentLoaded", () => {
            console.log(document.cookie)

            if (window.location.pathname.slice(-1) === "/" && !document.cookie.includes("isButtonClicked=true")) {
                const registerButton = document.querySelector("#registerButton")
                registerButton.click()
                document.cookie = "isButtonClicked=true"
            }

            const form = document.querySelector("#form")
            if (form && !document.cookie.includes("isFormSubmited=true")) {
                document.querySelector("#email").value = "test@mail.com"
                document.querySelector("#password").value = "Password!1Asfw13"
                document.querySelector("#confirmPassword").value = "Password!1Asfw13"
                document.cookie = "isFormSubmited=true"
                form.submit()
            }
            console.log(window.location)
        })
    </script>
</head>

<body>
    <header id="header" class="fixed-top d-flex">
        <div class="container d-flex align-items-center">
            <h1 class="logo me-auto"><a asp-controller="Home" asp-action="Index">D&M</a></h1>

            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul class="align-items-center">
                    <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="nav-item"><a class="nav-link scrollto" href="#about">O nas</a></li>
                    <li class="nav-item"><a class="nav-link scrollto" href="#services">Nasze atuty</a></li>
                    <li class="nav-item"><a class="nav-link scrollto" href="#Opinion">Opinie</a></li>
                    <li class="nav-item"><a class="nav-link scrollto" href="#FAQ">FAQ</a></li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item"><a class="nav-link scrollto" asp-controller="Clients" asp-action="List">Lista zgłoszeń</a></li>
                    }
                        <li class="nav-item"><a class="nav-item active" asp-controller="Clients" asp-action="Index">Kontakt</a></li>
                        <partial name="_LoginPartial" />
                    </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav>
        </div>
    </header>


    @RenderBody()


    <footer id="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-md" align="center">
                        <div class="col-lg-3 col-md-6 footer-contact ">
                            <h3>D&M<span>.</span></h3>
                            <p>
                                Ulica Kropkowa 145 <br>
                                Kraków<br>
                                Polska <br><br>
                                <strong>Phone:</strong> 123456789<br>
                                <strong>Email:</strong> dotacjeunijne@gmail.com<br>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container d-md-flex py-4">

            <div class="me-md-auto text-center text-md-start">
                <div class="copyright">
                    &copy; Copyright <strong><span>D&M</span></strong>. All Rights Reserved
                </div>
            </div>

        </div>
    </footer>

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <script src="~/assets/vendor/purecounter/purecounter.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>

    <script src="~/assets/js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>@ViewData["Title"] Strona</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top d-flex align-items-center">
        <div class="container d-flex align-items-center">
            <h1 class="logo me-auto"><a asp-controller="Home" asp-action="Index">D&M<span>.</span></a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt=""></a>-->

            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    <li><a class="nav-link" asp-controller="Home" asp-action="Index">Home</a></li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->
            <a class="get-started-btn scrollto" asp-controller="Clients" asp-action="Index">Kontakt</a>
            <a class="get-started-btn scrollto" asp-controller="Home" asp-action="Admin">Logowanie</a>
        </div>
    </header><!-- End Header -->


    @RenderBody()

    <!-- ======= Footer ======= -->
    <footer id="footer">

        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-md" align="center">
                        <div class=" col-lg-3 col-md-6 footer-contact ">
                            <h3>D&M<span>.</span></h3>
                            <p>
                                Ulica Kropkowa 145 <br>
                                Kraków<br>
                                Polska <br><br>
                                <strong>Phone:</strong>123456789<br>
                                <strong>Email:</strong> dotacjeuijne@gmail.com<br>
                            </p>
                        </div>
                        </div>





                    </div>
                </div>
        </div>

        <div class="container d-md-flex py-4">

            <div class="me-md-auto text-center text-md-start">
                <div class="copyright">
                    &copy; Copyright <strong><span>D&M</span></strong>. All Rights Reserved
                </div>
            </div>
          
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/purecounter/purecounter.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>

Views/Shared/_Layout3.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>@ViewData["Title"] Strona</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top d-flex align-items-center">
        <div class="container d-flex align-items-center">
            <h1 class="logo me-auto"><a asp-controller="Home" asp-action="Index">D&M<span>.</span></a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt=""></a>-->

            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    <li><a class="nav-link" asp-controller="Home" asp-action="Index">Home</a></li>



                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->
            <a class="get-started-btn scrollto" asp-controller="Clients" asp-action="Index">Kontakt</a>
        </div>
    </header><!-- End Header -->


    @RenderBody()


    <!-- ======= Footer ======= -->
    <footer id="footer">

        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-md" align="center">
                        <div class=" col-lg-3 col-md-6 footer-contact ">
                            <h3>D&M<span>.</span></h3>
                            <p>
                                Ulica Kropkowa 145 <br>
                                Kraków<br>
                                Polska <br><br>
                                <strong>Phone:</strong> 123456789<br>
                                <strong>Email:</strong> dotacjeunijne@gmail.com<br>
                            </p>
                        </div>
                        </div>




                    </div>
            </div>
        </div>

        <div class="container d-md-flex py-4">

            <div class="me-md-auto text-center text-md-start">
                <div class="copyright">
                    &copy; Copyright <strong><span>D&M</span></strong>. All Rights Reserved
                </div>
            </div>
    
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/purecounter/purecounter.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>

Views/Shared/_LayoutHeaderNonEx.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>@ViewData["Title"] Strona</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <link href="~/assets/css/style.css" rel="stylesheet">

</head>

<body>

    <header id="header" class="fixed-top d-flex">
        <div class="container d-flex align-items-center">
            <h1 class="logo me-auto"><a asp-controller="Home" asp-action="Index">D&M</a></h1>
            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul class="align-items-center">
                    <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">Home</a></li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item"><a class="nav-link scrollto" asp-controller="Clients" asp-action="List">Lista zgłoszeń</a></li>
                    }
                    <li class="nav-item"><a class="nav-item active" asp-controller="Clients" asp-action="Index">Kontakt</a></li>
                    <partial name="_LoginPartial" />
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav>
        </div>
    </header>

    @RenderBody()

    <footer id="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-md" align="center">
                        <div class=" col-lg-3 col-md-6 footer-contact ">
                            <h3>D&M<span>.</span></h3>
                            <p>
                                Ulica Kropkowa 145 <br>
                                Kraków<br>
                                Polska <br><br>
                                <strong>Phone:</strong>123456789<br>
                                <strong>Email:</strong> dotacjeuijne@gmail.com<br>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container d-md-flex py-4">
            <div class="me-md-auto text-center text-md-start">
                <div class="copyright">
                    &copy; Copyright <strong><span>D&M</span></strong>. All Rights Reserved
                </div>
            </div>
        </div>
    </footer>

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <script src="~/assets/vendor/purecounter/purecounter.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>

    <script src="~/assets/js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>

Views/Shared/_LayoutLogin.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>@ViewData["Title"] Strona</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <link href="~/assets/css/style.css" rel="stylesheet">

</head>

<body>

    <header id="header" class="fixed-top d-flex">
        <div class="container d-flex align-items-center">
            <h1 class="logo me-auto"><a asp-controller="Home" asp-action="Index">D&M</a></h1>
            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul class="align-items-center">
                    <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">Home</a></li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item"><a class="nav-link scrollto" asp-controller="Clients" asp-action="List">Lista zgłoszeń</a></li>
                    }
                    <li class="nav-item"><a class="nav-item active" asp-controller="Clients" asp-action="Index">Kontakt</a></li>
                    <partial name="_LoginPartial" />
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav>
        </div>
    </header>


                @RenderBody()



    <footer id="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-md" align="center">
                        <div class=" col-lg-3 col-md-6 footer-contact ">
                            <h3>D&M<span>.</span></h3>
                            <p>
                                Ulica Kropkowa 145 <br>
                                Kraków<br>
                                Polska <br><br>
                                <strong>Phone:</strong> 123456789<br>
                                <strong>Email:</strong> dotacjeunijne@gmail.com<br>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container d-md-flex py-4">
            <div class="me-md-auto text-center text-md-start">
                <div class="copyright">
                    &copy; Copyright <strong><span>D&M</span></strong>. All Rights Reserved
                </div>
            </div>

        </div>
    </footer>

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <script src="~/assets/vendor/purecounter/purecounter.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>

    <script src="~/assets/js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>